
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --

#include <cdk/ast/all.h>


#ifdef __NODE_DECLARATIONS_ONLY__

namespace udf {

class address_node;
class block_node;
class break_node;
class continue_node;
class evaluation_node;
class for_node;
class function_call_node;
class function_declaration_node;
class function_definition_node;
class if_else_node;
class if_node;
class index_node;
class input_node;
class nullptr_node;
class return_node;
class sizeof_node;
class stack_alloc_node;
class tensor_capacity_node;
class tensor_contract_node;
class tensor_dimension_node;
class tensor_dimensions_node;
class tensor_index_node;
class tensor_node;
class tensor_rank_node;
class tensor_reshape_node;
class variable_declaration_node;
class write_node;


} // namespace udf

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_udf_NODE_ALL_NODES_H__
#define __AUTOMATIC_udf_NODE_ALL_NODES_H__

#include "ast/address_node.h"
#include "ast/block_node.h"
#include "ast/break_node.h"
#include "ast/continue_node.h"
#include "ast/evaluation_node.h"
#include "ast/for_node.h"
#include "ast/function_call_node.h"
#include "ast/function_declaration_node.h"
#include "ast/function_definition_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/index_node.h"
#include "ast/input_node.h"
#include "ast/nullptr_node.h"
#include "ast/return_node.h"
#include "ast/sizeof_node.h"
#include "ast/stack_alloc_node.h"
#include "ast/tensor_capacity_node.h"
#include "ast/tensor_contract_node.h"
#include "ast/tensor_dimension_node.h"
#include "ast/tensor_dimensions_node.h"
#include "ast/tensor_index_node.h"
#include "ast/tensor_node.h"
#include "ast/tensor_rank_node.h"
#include "ast/tensor_reshape_node.h"
#include "ast/variable_declaration_node.h"
#include "ast/write_node.h"


#endif /* !defined(__AUTOMATIC_udf_NODE_ALL_NODES_H__) */
#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

