
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_address_node(udf::address_node *const node, int lvl) = 0;
  virtual void do_block_node(udf::block_node *const node, int lvl) = 0;
  virtual void do_break_node(udf::break_node *const node, int lvl) = 0;
  virtual void do_continue_node(udf::continue_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(udf::evaluation_node *const node, int lvl) = 0;
  virtual void do_for_node(udf::for_node *const node, int lvl) = 0;
  virtual void do_function_call_node(udf::function_call_node *const node, int lvl) = 0;
  virtual void do_function_declaration_node(udf::function_declaration_node *const node, int lvl) = 0;
  virtual void do_function_definition_node(udf::function_definition_node *const node, int lvl) = 0;
  virtual void do_if_else_node(udf::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(udf::if_node *const node, int lvl) = 0;
  virtual void do_index_node(udf::index_node *const node, int lvl) = 0;
  virtual void do_input_node(udf::input_node *const node, int lvl) = 0;
  virtual void do_nullptr_node(udf::nullptr_node *const node, int lvl) = 0;
  virtual void do_return_node(udf::return_node *const node, int lvl) = 0;
  virtual void do_sizeof_node(udf::sizeof_node *const node, int lvl) = 0;
  virtual void do_stack_alloc_node(udf::stack_alloc_node *const node, int lvl) = 0;
  virtual void do_tensor_capacity_node(udf::tensor_capacity_node *const node, int lvl) = 0;
  virtual void do_tensor_contract_node(udf::tensor_contract_node *const node, int lvl) = 0;
  virtual void do_tensor_dimension_node(udf::tensor_dimension_node *const node, int lvl) = 0;
  virtual void do_tensor_dimensions_node(udf::tensor_dimensions_node *const node, int lvl) = 0;
  virtual void do_tensor_index_node(udf::tensor_index_node *const node, int lvl) = 0;
  virtual void do_tensor_node(udf::tensor_node *const node, int lvl) = 0;
  virtual void do_tensor_rank_node(udf::tensor_rank_node *const node, int lvl) = 0;
  virtual void do_tensor_reshape_node(udf::tensor_reshape_node *const node, int lvl) = 0;
  virtual void do_variable_declaration_node(udf::variable_declaration_node *const node, int lvl) = 0;
  virtual void do_write_node(udf::write_node *const node, int lvl) = 0;

#else
  void do_address_node(udf::address_node *const node, int lvl);
  void do_block_node(udf::block_node *const node, int lvl);
  void do_break_node(udf::break_node *const node, int lvl);
  void do_continue_node(udf::continue_node *const node, int lvl);
  void do_evaluation_node(udf::evaluation_node *const node, int lvl);
  void do_for_node(udf::for_node *const node, int lvl);
  void do_function_call_node(udf::function_call_node *const node, int lvl);
  void do_function_declaration_node(udf::function_declaration_node *const node, int lvl);
  void do_function_definition_node(udf::function_definition_node *const node, int lvl);
  void do_if_else_node(udf::if_else_node *const node, int lvl);
  void do_if_node(udf::if_node *const node, int lvl);
  void do_index_node(udf::index_node *const node, int lvl);
  void do_input_node(udf::input_node *const node, int lvl);
  void do_nullptr_node(udf::nullptr_node *const node, int lvl);
  void do_return_node(udf::return_node *const node, int lvl);
  void do_sizeof_node(udf::sizeof_node *const node, int lvl);
  void do_stack_alloc_node(udf::stack_alloc_node *const node, int lvl);
  void do_tensor_capacity_node(udf::tensor_capacity_node *const node, int lvl);
  void do_tensor_contract_node(udf::tensor_contract_node *const node, int lvl);
  void do_tensor_dimension_node(udf::tensor_dimension_node *const node, int lvl);
  void do_tensor_dimensions_node(udf::tensor_dimensions_node *const node, int lvl);
  void do_tensor_index_node(udf::tensor_index_node *const node, int lvl);
  void do_tensor_node(udf::tensor_node *const node, int lvl);
  void do_tensor_rank_node(udf::tensor_rank_node *const node, int lvl);
  void do_tensor_reshape_node(udf::tensor_reshape_node *const node, int lvl);
  void do_variable_declaration_node(udf::variable_declaration_node *const node, int lvl);
  void do_write_node(udf::write_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

